name: GitHub Stats

on:
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=fagpc044&show_icons=true&theme=discord_old_blurple
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=fagpc044&layout=compact&langs_count=5&theme=discord_old_blurple
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

      - name: Commit Stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/stats.svg
          git commit -m "Update GitHub stats" || exit 0
          git push
